# Generated by Django 3.2.5 on 2021-09-21 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('snippets', models.CharField(default='', max_length=250)),
                ('content', models.CharField(default='', max_length=250)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Blog',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainModule.postmodel')),
            ],
        ),
    ]
